// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Insert_MoreCustomerData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Insert_MoreCustomerData));
        
        string IMigrationMetadata.Id
        {
            get { return "201808070250374_Insert_MoreCustomerData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
